joy_node:
  ros__parameters:
    device_id: 0  # Use js0 (confirmed working)
    device_name: "Xbox 360 Controller"  # Use exact name from joy_node output
    deadzone: 0.05
    autorepeat_rate: 20.0
    default_trig_val: true  # Set default trigger value to 1.0 when not pressed

teleop_node:
  ros__parameters:
    #  Xbox 360 controller mapping:
    # Axes: 0=LeftStickX, 1=LeftStickY, 2=LeftTrigger, 3=RightStickX, 
    #       4=RightStickY, 5=RightTrigger, 6=DPadX, 7=DPadY
    axis_linear:
      x: 1  # Left stick up/down
    scale_linear:
      x: 2.0  # Increased from 1.0 for higher linear speed
    scale_linear_turbo:
      x: 4.0  # Increased from 2.0 for higher turbo speed

    axis_angular:
      yaw: 0  # Left stick left/right
    scale_angular:
      yaw: 4.0  # Increased from 3.0 for higher rotation speed
    scale_angular_turbo:
      yaw: 6.0  # Increased from 4.0 for higher turbo rotation speed

    # Xbox 360 buttons: 
    # 0=A, 1=B, 2=X, 3=Y, 4=LB, 5=RB, 6=Back/Select, 7=Start, 
    # 8=Guide, 9=Left stick press, 10=Right stick press
    enable_button: 4  # LB button (TL on jstest)
    enable_turbo_button: 5  # RB button (TR on jstest)
    
    require_enable_button: false
    
    stamped: false
    frame_id: "base_link"