joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 5  # Working axis for forward/backward
    scale_linear:
      x: 0.7  # Increased from 0.5 for better response
    scale_linear_turbo:
      x: 1.2  # Increased for turbo mode

    axis_angular:
      yaw: 2  # Working axis for turning
    scale_angular:
      yaw: 4.0  # Increased to 4.0 as you suggested
    scale_angular_turbo:
      yaw: 5.0  # Even higher for turbo mode

    # Try different enable buttons
    enable_button: 5  # RB button works
    # Alternative enable buttons to try:
    # 1: B button
    # 2: X button  
    # 3: Y button
    # 4: LB button
    # 5: RB button
    # 6: Select button
    # 7: Start button
    
    enable_turbo_button: 7  # Start button for turbo
    require_enable_button: true
    
    stamped: false
    frame_id: "base_link"