joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left stick up/down (verified working)
    scale_linear:
      x: 0.7  # Good responsive speed
    scale_linear_turbo:
      x: 1.2  # Faster in turbo mode

    axis_angular:
      yaw: 0  # Left stick left/right for rotation
    scale_angular:
      yaw: 4.0  # Higher rotation speed
    scale_angular_turbo:
      yaw: 5.0  # Even higher for turbo mode

    # Working buttons
    enable_button: 4  # LB button (confirmed working)
    enable_turbo_button: 7  # Start button (confirmed working)
    
    require_enable_button: true
    
    stamped: false  # Changed to false since this works with your controller
    frame_id: "base_link"