joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0


    enable_button: 6  # BTN_SELECT (314) on Xbox 360 controller
    enable_turbo_button: 7  # BTN_START (315) on Xbox 360 controller

    require_enable_button: true
    
    stamped: false
    frame_id: "base_link"