slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: localization

    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    map_file_name: /home/bose/dev_ws/new_map_serial
    map_start_pose: [0.0, 0.0, 0.0]
    map_start_at_dock: true  # Commented out as it can cause issues with mapping mode

    debug_logging: false
    throttle_scans: 2
    transform_publish_period: 0.02
    map_update_interval: 1.0
    resolution: 0.05
    min_laser_range: 0.15  # Adjusted to match LiDAR min range
    max_laser_range: 12.0
    minimum_time_interval: 0.1
    transform_timeout: 0.5  # Increased for more reliable transforms
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
    enable_interactive_mode: false

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1  # Increased to reduce unnecessary updates
    minimum_travel_heading: 0.1  # Increased to reduce unnecessary updates
    scan_buffer_size: 50
    scan_buffer_maximum_scan_distance: 12.0
    link_match_minimum_response_fine: 0.3  # Increase for more robust loop closure
    link_scan_maximum_distance: 2.0
    loop_search_maximum_distance: 10.0  # Increase for better loop closure
    do_loop_closing: true 
    loop_match_minimum_chain_size: 8
    loop_match_maximum_variance_coarse: 2.0
    loop_match_minimum_response_coarse: 0.5  # Increase for more robust loop closure
    loop_match_minimum_response_fine: 0.5

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.2
    angle_variance_penalty: 0.5

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
