controller_manager:
  ros__parameters:
    update_rate: 200  # Hz - Increased for smoother control

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.31
    wheel_radius: 0.055
    
    # Additional wheel parameters
    wheel_separation_multiplier: 1.0  # Keep at 1.0 for accurate odometry
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Odometry covariances for the encoder output of the robot
    pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.1, 0.1, 0.1]  # Increased for more realistic error modeling
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.1, 0.1, 0.1]  # Increased for more realistic error modeling

    use_stamped_vel: false

    # Velocity and acceleration limits - increased for better responsiveness
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: true
    linear.x.max_velocity: 1.0  # m/s - increased from 0.5
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 0.5 # m/s^2 - increased from 0.2
    linear.x.min_acceleration: -0.5
    linear.x.max_jerk: 0.8  # m/s^3 - increased from 0.3
    linear.x.min_jerk: -0.8

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: true
    angular.z.max_velocity: 2.0  # rad/s - increased from 1.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 1.0  # rad/s^2 - increased from 0.4
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 1.5  # rad/s^3 - increased from 0.7
    angular.z.min_jerk: -1.5

    # Odometry frame configuration
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"  # Matches SLAM config
    publish_odom: true
    publish_odom_tf: true
    publish_wheel_tf: true  # Enable wheel TF publishing for more complete TF tree
    
    # Topic configuration
    odom_topic: "/diff_cont/odom"
    cmd_vel_topic: "/cmd_vel"
    
    # Additional stability parameters
    position_feedback: true
    open_loop: false  # Set to false for closed-loop control with encoder feedback
    enable_odom_tf: true
    publish_rate: 200.0  # Hz - Match update_rate for consistent timing
    cmd_vel_timeout: 0.5
