controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    diff_cont:
      type: diff_drive_controller/DiffDriveController
  
diff_cont:
  ros__parameters:
    base_frame_id: base_link
    
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    
    wheel_separation: 0.255
    wheel_radius: 0.0575
    
    use_stamped_vel: false
    
    # Transform synchronization parameters
    publish_rate: 50.0  # Hz - Ensure this matches the controller_manager update_rate
    enable_odom_tf: true
    
    # Speed limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5  # m/s
        min_velocity: -0.5  # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # m/s^2
        min_acceleration: -1.0  # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        min_velocity: -1.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2
        min_acceleration: -2.0  # rad/s^2 