controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:
    left_wheel_names: 
      - left_wheel_joint
    right_wheel_names: 
      - right_wheel_joint
    
    wheel_separation: 0.255
    wheel_radius: 0.0575
    
    # Encoder parameters
    left_wheel_encoder_ticks_per_meter: 3798.7
    right_wheel_encoder_ticks_per_meter: 3862.8
    
    # Odometry parameters
    base_frame_id: base_footprint
    odom_frame_id: odom
    pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    
    # Other parameters  
    publish_rate: 100.0
    use_stamped_vel: false
    
    # Enable TF publishing and disable diff_tf
    enable_odom_tf: true
    publish_odom: true
    
    # Velocity command limits
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.5
    linear.x.min_velocity: -0.5
    angular.z.has_velocity_limits: true  
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0 