teleop_twist_joy_node:
  ros__parameters:
    # Default settings for most joystick types with sensible defaults
    # Default is for Xbox/PS4-style controllers
    
    # Axes configurations for velocity commands
    axis_linear:
      x: 1     # Left stick up/down
    axis_angular:
      yaw: 0   # Left stick left/right
    
    # Speed scaling for precision control
    scale_linear:
      x: 0.5      # 0.5 m/s max
    scale_angular:
      yaw: 1.0    # 1.0 rad/s max
    
    # Turbo mode for higher speeds (when turbo button pressed)
    scale_linear_turbo:
      x: 1.0      # 1.0 m/s max
    scale_angular_turbo:
      yaw: 2.0    # 2.0 rad/s max
    
    # Button configurations
    enable_button: 5    # Right shoulder button (RB on Xbox)
    enable_turbo_button: 4   # Left shoulder button (LB on Xbox)
    
    # Control settings
    require_enable_button: true    # Requires the enable button to be pressed for movement

# Alternative PS4 controller configuration
# Use: ros2 param set /teleop_twist_joy_node joy_config "ps4"
joy_configs:
  ps4:
    axis_linear:
      x: 1       # Left stick up/down
    axis_angular: 
      yaw: 2     # Right stick left/right
    enable_button: 5     # R1 button
    enable_turbo_button: 7  # R2 button

  # Alternative Logitech F710 controller configuration
  # Use: ros2 param set /teleop_twist_joy_node joy_config "f710"
  f710:
    axis_linear:
      x: 1       # Left stick up/down 
    axis_angular:
      yaw: 0     # Left stick left/right
    enable_button: 5     # RB button
    enable_turbo_button: 7  # RT button 